spring:
  application:
    name: attendance
  datasource:
    # Prefer env (PostgreSQL). Fallback to in-memory H2 for local dev.
    # Example PostgreSQL URL: jdbc:postgresql://HOST:5432/DB?sslmode=require
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:attendancedb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8080
